name: saltstack-iscdhcp-formula
source: https://github.com/bechtoldt/saltstack-iscdhcp-formula
summary: SaltStack Formula to set up and configure ISC DHCP, the Internet Systems Consortium DHCP Server
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
